### ISSUE TITLE
1.0 release todo

### ISSUE THREAD

**Issue by masklinn** [ua-parser/uap-python#233]
- [x] pass over documentation and ensure it makes sense and doesn't suck too hard
- [x] pass over readme for the same reason, remove warning, consider adding more badges (?) / links
    - [x] doc badge
- [x] add readme to ua-parser-rs's pyproject.toml and cut a release because currently the pypi page is super sus
- [x] release workflow (#137, ideally #224 but that's not a requirement) + doc release workflow
- [x] publish ua-parser-builtins on pypi (latest tag + dev, and maybe a few historical tags because why not)
- [x] remove local install of ua-parser-builtins from the rtfd config (can be built using pypi's)
- [x] publish doc
- [x] Just out of abundance of caution: test that the 0.x readme works out of the box with the prerelease
- [x] #234
- [x] actually publish the 1.0 doc (as stable, not just latest)
- [x] switch default branch of doc to stable
